apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: payment
  labels:
    project: roboshop
    component: payment
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"