apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 5672 # service port
    targetPort: 5672 # container port