apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: web
spec:
  selector:   
    project: roboshop
    component: frontend
    tier: web   
  ports:
    - protocol: TCP
      port: 80      # The port the Service itself exposes
      targetPort: 8080 # container port
  type: LoadBalancer