apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app
spec:
  selector:   
    project: roboshop
    component: catalogue
    tier: app    
  ports:
    - protocol: TCP
      port: 8080       # The port the Service itself exposes
      targetPort: 8080 # container port
  type: ClusterIP